apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: ktaktak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "300m"
            memory: "300Mi"
          limits:
            cpu: "400m"
            memory: "400Mi"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "example"
        livenessProbe:  # Adding liveness probe here
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 5
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: ktaktak
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017        # Exposed port
    targetPort: 27017  # MongoDB container port
  type: ClusterIP
