apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: webnodb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
