global:
  namespace: ktaktak
  mongo:
    host: mongodb-0.mongodb-service.ktaktak.svc.cluster.local
    port: 27017
    username: root
    password: example

mongodb:
  resources:
    requests:
      cpu: "300m"
      memory: "300Mi"
    limits:
      cpu: "400m"
      memory: "400Mi"
  replicas: 1
  storage: 1Gi  


webdb:
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "200m"
      memory: "200Mi"
  replicas: 3

webnodb:
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "200m"
      memory: "200Mi"
  replicas: 2

ingress:
  class: nginx
  rules:
    - host: webnodb.ktaktak.net4255.luxbulb.org
      service: webnodb-service
      port: 80
    - host: webdb.ktaktak.net4255.luxbulb.org
      service: webdb-service
      port: 80


service:
  type: ClusterIP # Or NodePort/LoadBalancer depending on your setup
  port: 80

