apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: {{ .Values.global.mongo.port }}
    targetPort: {{ .Values.global.mongo.port }}
  type: ClusterIP
