apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: {{ .Values.global.namespace }}
data:
  MONGO_HOST: {{ .Values.global.mongo.host }}
  MONGO_PORT: "{{ .Values.global.mongo.port }}"
