apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: mongodb-service
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: {{ .Values.global.mongo.port }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.global.mongo.username }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.global.mongo.password }}
        resources:
          requests:
            cpu: {{ .Values.mongodb.resources.requests.cpu }}
            memory: {{ .Values.mongodb.resources.requests.memory }}
          limits:
            cpu: {{ .Values.mongodb.resources.limits.cpu }}
            memory: {{ .Values.mongodb.resources.limits.memory }}
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mongodb.storage }}
