version: '3.1'

services:
  flask-app-db:
    build:
      context: ./flask_db  
    restart: always
    ports:
      - "5001:5000"
    networks:
      - app_network
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/
  
  flask-app-nodb:
    build:
      context: ./flask_nodb  
    restart: always
    ports:
      - "5002:5000"
    networks:
      - app_network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - app_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app-db
      - flask-app-nodb

networks:
  app_network:

volumes:
  mongo_data:
