apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: ktaktak
spec:
  selector:
      app: webnodb
  ports:
  - protocol: TCP
    port: 80      # Service port
    targetPort: 5000 # Pod container port
  type: ClusterIP
